import React from 'react';
import {useResource,State,Field,Table} from './SharedUI';
import {Button} from '@/components/ui/button';
export const QueryMetrics=({range,setRange,search,requestType,onDrill})=>{
  const r=useResource('/requests/metrics/summary',{start:range.start,end:range.end,search,request_type:requestType},true),d=r.data;
  return <section className="detail-section"><h2>Enquiry reporting · IST</h2><div className="filters"><Field name="metrics-start" type="date" title="Reporting from" value={range.start} onChange={v=>setRange({...range,start:v})}/><Field name="metrics-end" type="date" title="Reporting to" value={range.end} onChange={v=>setRange({...range,end:v})}/></div><State resource={r} id="query-metrics"/>
    {d&&<><div className="metrics-strip">{Object.entries(d.received_cohort||{}).map(([k,v])=><div key={k}><span>Received cohort · {k}</span><strong data-testid={`cohort-${k}`}>{v}</strong></div>)}<div><span>Resolved in period · including older receipts</span><strong data-testid="period-throughput">{d.period_throughput}</strong></div></div>
    <p className="text-xs text-slate-500" data-testid="metrics-denominator">Status filters change the list only. Work-event days are not attendance. Reporting windows are at most 366 days, not lifetime totals.</p>
    <Table id="telecaller-metrics" rows={d.telecallers||[]} columns={[{key:'name',title:'Telecaller',render:u=><div className={u.top_performer?'top-performer':''}><Button variant="link" data-testid={`metric-open-${u.id}`} onClick={()=>onDrill(u.id,range.start,range.end)}>{u.name}</Button>{u.top_performer&&<p data-testid={`top-performer-${u.id}`}>Highest nonzero result</p>}</div>},{key:'resolved',title:'Handled / Team handled',render:u=>`${u.resolved} / ${u.team_resolved}`},{key:'resolved_from_assigned',title:'Handled from assigned / cohort',render:u=>`${u.resolved_from_assigned} / ${u.assigned_workload}`},{key:'open_workload',title:'Pending assigned cohort'},{key:'active_days',title:'Work days / Calendar days',render:u=>`${u.active_days} / ${u.calendar_days}`},{key:'daily',title:'Daily breakdown',render:u=><div className="space-y-1">{Object.entries(u.daily||{}).map(([day,v])=><Button key={day} variant="outline" data-testid={`metric-day-${u.id}-${day}`} onClick={()=>onDrill(u.id,day,day)}>{day}: {v.resolved} handled · {v.work_events} work events</Button>)}</div>}]}/></>}
  </section>;
};