import React,{useState} from 'react';
import {useResource,State,Table,Field,Notice,ist,duration} from './SharedUI';
import {Button} from '@/components/ui/button';
import {shared,errMsg} from '@/lib/api';
export const QueryDetail=({id,me,catalog,options,onClose,onChanged})=>{
  const r=useResource(`/requests/${id}/history`),[status,setStatus]=useState(''),[notes,setNotes]=useState(''),[assignee,setAssignee]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const q=r.data?.request;
  const mutate=async action=>{if(!q)return;setBusy(true);setError('');const body={version:q.version,action,idempotency_key:crypto.randomUUID()};if(action==='reopen')body.status='pending';else if(status&&action==='update')body.status=status;if(notes)body.notes=notes;if(action==='assign')body.assigned_to=assignee;
    try{await shared.write(action==='claim'?'post':'patch',`/requests/${id}${action==='claim'?'/claim':''}`,body);await r.load();onChanged();setNotes('');setStatus('');}catch(e){setError(errMsg(e));if(e.response?.status===409){await r.load();setStatus('');setNotes('');}}finally{setBusy(false);}};
  const canProcess=me.role==='admin'||(me.role==='telecaller'&&q?.assignee_id===me.id);
  return <section className="app-dialog" data-testid="query-detail"><div className="flex justify-between"><h2>Enquiry details</h2><Button variant="ghost" data-testid="query-close" onClick={onClose}>Close</Button></div><State resource={r} id="query-history"/><Notice id="query-mutation-error">{error}</Notice>
    {q&&<><p data-testid="query-detail-customer">{q.customer_name||q.user_name} · {q.customer_shop_name||q.shop_name} · {q.customer_location||q.user_city}</p><p data-testid="query-detail-status">{q.request_type} · {q.status} · v{q.version}</p><p data-testid="query-timing">Created {ist(q.created_at)} · Original age {duration(q.age_seconds)} · Pending cycle {duration(q.pending_seconds)} · Handling {duration(q.handling_seconds)}</p><p data-testid="query-attribution">Assignee: {q.assignee_name||options.find(u=>u.id===q.assignee_id)?.name||q.assignee_id||'Unassigned'} · Resolver: {q.resolver_name||options.find(u=>u.id===q.resolver_id)?.name||q.resolver_id||'Not resolved'}</p>
    <p className="mt-3" data-testid="query-customer-message">Customer request: {q.notes||'No note supplied'} · Preferred time: {q.preferred_time||'Not specified'} · Category: {q.category||'Not specified'}</p>
    {(q.linked_products||[]).length>0&&<Table id="query-linked-products" rows={q.linked_products} columns={[{key:'product_code',title:'SKU'},{key:'title',title:'Requested product'},{key:'category',title:'Category'},{key:'approx_weight',title:'Weight'}]}/>}
    {me.role!=='billing_executive'&&<div className="mt-4 space-y-3">{(catalog?.open_statuses||[]).includes(q.status)&&!q.assignee_id&&<Button disabled={busy} onClick={()=>mutate('claim')} data-testid="query-claim">Claim enquiry</Button>}
      {canProcess&&<><div className="fields-grid"><Field name="query-new-status" value={status} options={[{value:'',label:'Keep current'},...(catalog?.statuses||[]).filter(s=>s!=='pending'||!(catalog?.terminal_statuses||[]).includes(q.status))]} onChange={setStatus}/><Field name="query-note" title="Internal note" value={notes} onChange={setNotes}/></div><Button disabled={busy||(!status&&!notes)} onClick={()=>mutate('update')} data-testid="query-save">Save update</Button>{(catalog?.terminal_statuses||[]).includes(q.status)&&<Button disabled={busy} variant="outline" onClick={()=>mutate('reopen')} data-testid="query-reopen">Reopen to pending</Button>}</>}
      {me.role==='admin'&&<div className="flex flex-wrap gap-2"><Field name="query-assign" title="Assign active telecaller" options={[{value:'',label:'Unassigned'},...options.filter(u=>u.role==='telecaller'&&u.status==='active').map(u=>({value:u.id,label:u.name}))]} value={assignee} onChange={setAssignee}/><Button disabled={busy} data-testid="query-assign-save" onClick={()=>mutate('assign')}>Assign</Button></div>}
    </div>}
    <Table id="query-events" rows={r.data.history||[]} columns={[{key:'type',title:'Event'},{key:'actor_name',title:'Actor'},{key:'timestamp',title:'Time',render:e=>ist(e.timestamp)},{key:'status',title:'Status'},{key:'notes',title:'Notes'}]}/></>}
  </section>;
};