import React,{useState} from 'react';
import {useResource,State,Table,Field,Notice,ist,duration,label} from './SharedUI';
import {PrivateImage} from './PrivateImage';
import {Button} from '@/components/ui/button';
import {shared,errMsg} from '@/lib/api';
import {phoneDisplay} from '@/lib/phone';
const OUTCOMES=[['converted','Converted'],['not_interested','Not interested'],['other','Other']];
const key=()=>(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`);
// datetime-local values are entered in IST and sent as ISO-8601 with the +05:30 offset; stored ISO is shown back in IST.
export const fromIST=local=>local?`${local}:00+05:30`:'';
export const toISTLocal=iso=>{if(!iso)return '';const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(iso)).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour==='24'?'00':p.hour}:${p.minute}`;};

export const QueryDetail=({id,me,catalog,options,onClose,onChanged})=>{
  const d=useResource(`/requests/${id}`,{},true),h=useResource(`/requests/${id}/history`);const q=d.data,perms=q?.permissions||{};
  const [head,setHead]=useState(''),[notes,setNotes]=useState(''),[follow,setFollow]=useState(null),[outcome,setOutcome]=useState('other'),[reason,setReason]=useState(''),[assignee,setAssignee]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[info,setInfo]=useState('');
  const open=q&&(catalog?.open_statuses||['pending','in_progress','contacted','no_response']).includes(q.status),terminal=q&&(catalog?.terminal_statuses||['resolved','cancelled']).includes(q.status);
  const reload=async()=>{const fresh=await d.load();h.load();onChanged&&onChanged();return fresh;};
  const mutate=async(action,body={})=>{if(!q)return null;setBusy(true);setError('');setInfo('');
    try{const res=await shared.write('patch',`/requests/${id}`,{version:q.version,action,idempotency_key:key(),...body});await reload();return res;}
    catch(e){setError(errMsg(e));if(e.response?.status===409)await reload();return null;}finally{setBusy(false);}};
  const take=async()=>{const res=await mutate('claim');if(res)setInfo(res.already_claimed?'You already hold this query.':'You hold this query now.');return res;};
  // Call / WhatsApp on an unclaimed open query: claim first, re-check the current holder, then open the link.
  const contact=async kind=>{let cur=q;if(open&&!q.assignee_id&&perms.can_claim){if(!await mutate('claim'))return;cur=await d.load();if(!cur||cur.assignee_id!==me.id){setError(`${cur?.assignee_name||'Another telecaller'} took this query first.`);return;}}
    const target=kind==='tel'?`tel:${cur.contact?.tel}`:`https://wa.me/${cur.contact?.whatsapp}`;if(cur.contact?.[kind==='tel'?'tel':'whatsapp'])window.open(target,'_blank','noopener');};
  const save=()=>{const body={};if(head&&head!==q.head)body.head=head;if(notes.trim())body.notes=notes.trim();if(follow!==null)body.follow_up_at=fromIST(follow);return mutate('update',body).then(r=>{if(r){setHead('');setNotes('');setFollow(null);}});};
  const held=q&&q.assignee_id&&q.assignee_id!==me.id,canAct=perms.can_work||perms.can_claim;
  const assignable=options.filter(u=>['telecaller','admin'].includes(u.role)&&(u.account_status||u.status)==='active'&&u.id!==q?.assignee_id);
  return <section className="app-dialog" data-testid="query-detail"><div className="flex justify-between"><h2>Enquiry details</h2><Button variant="ghost" data-testid="query-close" onClick={onClose}>Close</Button></div><State resource={d} id="query-detail"/><Notice id="query-mutation-error">{error}</Notice>{info&&<p className="rounded-md border border-emerald-300 bg-emerald-50 px-4 py-2 text-sm text-emerald-900" role="status" data-testid="query-info">{info}</p>}
    {q&&<>
      <div className="grid gap-3 md:grid-cols-2 mt-3 text-sm">
        <div><p data-testid="query-detail-customer"><strong>{q.customer_name||q.user_name||'Unknown'}</strong>{q.customer_deleted&&' (deleted account)'}<br/>{q.customer_shop_name||q.shop_name||'—'} · {q.customer_location||q.user_city||'—'}</p>
          <p data-testid="query-detail-phone">{q.customer_deleted?'Number removed on deletion':q.customer_phone_display||phoneDisplay(q.user_phone||q.customer_phone)}</p>
          {q.customer?.lead_status&&<p className="text-xs text-slate-500" data-testid="query-detail-lead">Customer lead state (separate from this query's head): {label(q.customer.lead_status)} · {q.other_requests} other enquir{q.other_requests===1?'y':'ies'}</p>}</div>
        <div><p data-testid="query-detail-status">{label(q.request_type)} · <strong>{q.status==='resolved'?`Completed · ${label(q.outcome||'other')}`:`${q.head_label||label(q.head)} · ${label(q.status)}`}</strong> · v{q.version}</p>
          <p data-testid="query-timing">Created {ist(q.created_at)} · Age {duration(q.age_seconds)} · Pending cycle {duration(q.pending_seconds)} · Handling {duration(q.handling_seconds)}</p>
          <p data-testid="query-attribution">Holder: <strong data-testid="query-holder">{q.assignee_name||options.find(u=>u.id===q.assignee_id)?.name||(q.assignee_id?'Staff':'Unassigned')}</strong> · Completed by: {q.resolver_name||q.completed_by_name||'—'}{q.follow_up_at&&<> · Follow-up <strong data-testid="query-follow-up">{ist(q.follow_up_at)}</strong></>}{q.reset_count?` · released ${q.reset_count}× at 03:00`:''}</p></div>
      </div>
      <p className="mt-3 text-sm" data-testid="query-customer-message">Customer request: {q.notes||'No note supplied'} · Preferred time: {q.preferred_time||'Not specified'} · Category: {q.category||'Not specified'}</p>
      {(q.items||[]).length>0&&<div className="mt-3" data-testid="query-items"><h3 className="text-sm font-semibold">Requested items</h3><div className="grid gap-3 mt-2" style={{gridTemplateColumns:'repeat(auto-fill,minmax(150px,1fr))'}}>{q.items.map(it=><div key={it.product_id} className="rounded border p-2 text-xs" data-testid={`query-item-${it.product_id}`}>{it.available&&(it.thumbnail_path||it.storage_path||it.images?.[0])?<PrivateImage id={`query-item-photo-${it.product_id}`} src={it.thumbnail_path||it.storage_path||it.images?.[0]} alt={it.title}/>:<div className="photo-box"><span className="text-xs p-3 block" data-testid={`query-item-unavailable-${it.product_id}`}>{it.available?'No photo':'No longer listed · photo withheld'}</span></div>}<p className="mt-1 font-semibold break-words">{it.title}</p><p>{it.product_code||'—'} · {it.metal_type||'—'}{it.weight?` · ${it.weight}`:''} · qty {it.quantity}</p>{it.notes&&<p className="text-slate-500">{it.notes}</p>}</div>)}</div></div>}
      {canAct&&<div className="mt-4 space-y-3" data-testid="query-actions">
        {held&&me.role!=='admin'&&<p className="text-xs text-slate-600" data-testid="query-held-by-other">Held by {q.assignee_name||'another telecaller'} — view only. Only the holder or an administrator can work it.</p>}
        <div className="flex flex-wrap gap-2">{perms.can_claim&&<Button disabled={busy} onClick={take} data-testid="query-claim">Take this query</Button>}
          {perms.can_claim&&open&&!q.assignee_id&&<span className="text-xs text-slate-500 self-center" data-testid="query-claim-note">Call / WhatsApp take the query first, then open the link.</span>}
          {(perms.can_work||perms.can_claim)&&!q.customer_deleted&&q.contact?.tel&&<Button variant="outline" disabled={busy||(held&&!perms.can_work)} onClick={()=>contact('tel')} data-testid="query-call">Call {q.contact.tel}</Button>}
          {(perms.can_work||perms.can_claim)&&!q.customer_deleted&&q.contact?.whatsapp&&<Button variant="outline" disabled={busy||(held&&!perms.can_work)} onClick={()=>contact('whatsapp')} data-testid="query-whatsapp">{q.request_type==='video_call'?'Open WhatsApp chat (use its video button)':'WhatsApp'}</Button>}</div>
        {perms.can_work&&open&&<><div className="fields-grid"><Field name="query-head-select" title="Query head" options={[{value:'',label:`Keep ${q.head_label||label(q.head)}`},...(catalog?.heads||[]).map(x=>({value:x,label:catalog?.head_labels?.[x]||label(x)}))]} value={head} onChange={setHead}/><Field name="query-note" title="Staff note" value={notes} onChange={setNotes}/><label className="field" htmlFor="query-follow-up-input"><span>Follow-up · IST</span><input id="query-follow-up-input" data-testid="query-follow-up-input" type="datetime-local" className="h-10 rounded-md border border-input bg-white px-3 text-sm" value={follow??toISTLocal(q.follow_up_at)} onChange={e=>setFollow(e.target.value)}/>{(follow||q.follow_up_at)&&<Button variant="link" size="sm" className="h-auto p-0 justify-start" data-testid="query-follow-up-clear" onClick={()=>setFollow('')}>Clear follow-up</Button>}</label></div>
          <div className="flex flex-wrap items-end gap-2"><Button disabled={busy||(!head&&!notes.trim()&&follow===null)} onClick={save} data-testid="query-save">Save head / note / follow-up</Button>
            <Field name="query-outcome" title="Outcome" options={OUTCOMES.map(([v,l])=>({value:v,label:l}))} value={outcome} onChange={setOutcome}/><Button variant="outline" disabled={busy} onClick={()=>mutate('complete',{outcome,...(notes.trim()?{notes:notes.trim()}:{})}).then(r=>{if(r)setInfo('Marked complete — it left the pending list and stays in your completed history.');})} data-testid="query-complete">Mark complete</Button></div></>}
        {(perms.can_assign||perms.can_reopen)&&<div className="rounded border p-3 space-y-2" data-testid="query-admin-actions"><Field name="query-reason" title="Reason (at least 5 characters, recorded in history)" value={reason} onChange={setReason}/>
          <div className="flex flex-wrap items-end gap-2">{perms.can_assign&&open&&<><Field name="query-assign" title="Reassign to" options={[{value:'',label:'Choose staff'},...assignable.map(u=>({value:u.id,label:`${u.name} (${label(u.role)})`}))]} value={assignee} onChange={setAssignee}/><Button variant="outline" disabled={busy||!assignee||reason.trim().length<5} data-testid="query-assign-save" onClick={()=>mutate('assign',{assigned_to:assignee,reason:reason.trim()}).then(r=>{if(r){setAssignee('');setReason('');}})}>Reassign</Button></>}
            {perms.can_assign&&open&&q.assignee_id&&<Button variant="outline" disabled={busy||reason.trim().length<5} data-testid="query-release" onClick={()=>mutate('release',{reason:reason.trim()}).then(r=>{if(r)setReason('');})}>Release to queue</Button>}
            {perms.can_reopen&&terminal&&<Button variant="outline" disabled={busy||reason.trim().length<5} data-testid="query-reopen" onClick={()=>mutate('reopen',{status:'pending',reason:reason.trim()}).then(r=>{if(r)setReason('');})}>Reopen to pending</Button>}</div></div>}
      </div>}
      {!canAct&&<p className="mt-3 text-xs text-slate-500" data-testid="query-read-only">Read-only view for your role.</p>}
      {(q.completions||[]).length>0&&<Table id="query-completions" rows={q.completions.map(c=>({...c,id:c.id||c.key}))} columns={[{key:'completed_at',title:'Completed · IST',render:c=>ist(c.completed_at)},{key:'actor_name',title:'By'},{key:'outcome',title:'Outcome',render:c=>label(c.outcome)},{key:'superseded_at',title:'Counted',render:c=>c.superseded_at?`No · reopened ${ist(c.superseded_at)}`:'Yes'}]}/>}
      <State resource={h} id="query-history"/>
      <Table id="query-events" rows={h.data?.history||[]} columns={[{key:'type',title:'Event',render:e=>label(e.type)},{key:'actor_name',title:'Actor'},{key:'timestamp',title:'Time',render:e=>ist(e.timestamp)},{key:'status',title:'Status',render:e=>label(e.status)},{key:'new',title:'Change',render:e=>e.old||e.new?`${e.old??'—'} → ${e.new??'—'}`:'—'},{key:'notes',title:'Notes'}]}/></>}
  </section>;
};
