import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {PageTitle,State,useResource,Field,Table,Notice} from '@/components/admin/SharedUI';
import {Button} from '@/components/ui/button';
import {shared,errMsg} from '@/lib/api';
import {BatchImages} from '@/components/admin/BatchImages';
export default function Batches(){const r=useResource('/batches'),[name,setName]=useState(''),[error,setError]=useState(''),[batch,setBatch]=useState(null);
 const write=async(method,path,body)=>{try{await shared.write(method,path,body);setName('');setError('');await r.load();}catch(e){setError(errMsg(e));}};
 return <><PageTitle>Batches</PageTitle><State resource={r} id="batches"/><Notice id="batches-error">{error}</Notice><p className="text-xs mt-3" data-testid="batch-list-limit">Canonical batch directory: up to 200 non-archived batches. Not an uncapped inventory.</p><div className="filters"><Field name="batch-name" title="New batch name" value={name} onChange={setName}/></div><Button disabled={!name.trim()} data-testid="batch-create" onClick={()=>write('post','/batches',{name,metal_type:'silver',category:''})}>Create batch</Button>
 <Table id="batches" rows={r.data?.batches||[]} columns={[{key:'name',title:'Batch'},{key:'status',title:'Status'},{key:'image_count',title:'Image count'},{key:'actions',title:'Actions',render:b=><div className="flex flex-wrap gap-2"><Button variant="outline" data-testid={`batch-images-${b.id}`} onClick={()=>setBatch(b)}>View products</Button><Button variant="outline" data-testid={`batch-visibility-${b.id}`} onClick={()=>{if(window.confirm('Change visibility for every live product in this batch?'))write('patch',`/batches/${b.id}/visibility`,{});}}>{b.status==='visible'?'Hide batch':'Publish batch'}</Button><Button variant="outline" data-testid={`batch-rename-${b.id}`} onClick={()=>{const n=window.prompt('Batch name',b.name);if(n?.trim())write('put',`/batches/${b.id}`,{name:n});}}>Rename</Button><Button variant="ghost" data-testid={`batch-archive-${b.id}`} onClick={()=>{if(window.confirm('Archive this batch and soft-delete its products? Media erasure is not included.'))write('delete',`/batches/${b.id}`);}}>Archive</Button></div>}]}/>{batch&&<BatchImages batch={batch} onClose={()=>setBatch(null)} onChanged={r.load}/>}<Link className="underline inline-block mt-5" to="/admin/pdf-import" data-testid="batch-reviewed-import">Open reviewed PDF import</Link></>;
}