import React,{useEffect,useState} from 'react';
import {PageTitle,Notice,Table} from '@/components/admin/SharedUI';
import {NEW_PRODUCT,ProductFields} from '@/components/admin/ProductFields';
import {PrivateImage} from '@/components/admin/PrivateImage';
import {api,download,errMsg} from '@/lib/api';
import {Button} from '@/components/ui/button';
export default function CatalogAuthor(){
 const [form,setForm]=useState({...NEW_PRODUCT}),[photo,setPhoto]=useState(null),[entries,setEntries]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const warn=e=>{if(entries.length||photo){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[entries,photo]);
 const upload=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8*1024*1024){setError('Image limit is 8 MiB.');return;}setBusy(true);try{const d=new FormData();d.append('file',file);const r=await api.post('/bff/products/upload-image',d);setPhoto({...r.data,inputBytes:file.size});setError('');}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
 const add=()=>{if(!photo||!form.product_code||!form.title||!form.category){setError('Product code, name, category and photograph are required.');return;}if(entries.some(p=>p.product_code===form.product_code)){setError('Product codes must be unique.');return;}if(entries.reduce((n,p)=>n+p.inputBytes,0)+photo.inputBytes>32*1024*1024){setError('Export input photos exceed 32 MiB.');return;}setEntries([...entries,{...form,photo_path:photo.storage_path,inputBytes:photo.inputBytes}]);setForm({...NEW_PRODUCT});setPhoto(null);setError('');};
 const exportPDF=async()=>{setBusy(true);setError('');try{await download('/pdf-template/export','Yash-Catalog-v1.pdf',{products:entries.map(({inputBytes,...p})=>p)});}catch(e){if(e.response?.data instanceof Blob){try{setError(JSON.parse(await e.response.data.text()).detail);}catch{setError('PDF export failed.');}}else setError(errMsg(e));}finally{setBusy(false);}};
 return <><PageTitle>Catalog authoring</PageTitle><p className="text-sm" data-testid="authoring-scope">Session-only entries · up to 20 products and 32 MiB input photos. Leaving loses unsaved entries. Export creates a PDF, not catalog inventory.</p><Notice id="authoring-error">{error}</Notice><ProductFields value={form} onChange={setForm} prefix="author"/><label className="field">Product photograph<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} disabled={busy} data-testid="author-photo-upload"/></label>{photo&&<div className="max-w-xs my-4"><PrivateImage src={photo.url} id="author-photo-preview"/></div>}<Button className="mt-4" disabled={busy||entries.length>=20} onClick={add} data-testid="author-add-entry">Add to PDF</Button>
 <Table id="author-entries" rows={entries.map((e,i)=>({...e,id:String(i)}))} columns={[{key:'product_code',title:'SKU'},{key:'title',title:'Product'},{key:'metal_type',title:'Metal'},{key:'remove',title:'Remove',render:e=><Button variant="ghost" data-testid={`author-remove-${e.id}`} onClick={()=>setEntries(entries.filter((_,i)=>String(i)!==e.id))}>Remove</Button>}]}/><Button className="mt-5" disabled={busy||!entries.length} data-testid="author-export" onClick={exportPDF}>{busy?'Please wait…':'Export version 1 PDF'}</Button></>;
}