import React,{useState} from 'react';
import {PageTitle,State,useResource,Field,Table,Pager,Notice,ist} from '@/components/admin/SharedUI';
import {shared,errMsg} from '@/lib/api';
import {Button} from '@/components/ui/button';
export default function Leads(){
 const [f,setF]=useState({page:1,limit:20}),r=useResource('/telecaller/customers',f),[person,setPerson]=useState(null),[form,setForm]=useState({action:'note',notes:'',new_status:'',follow_up_at:''}),[error,setError]=useState('');const activity=useResource(person?`/telecaller/customers/${person.id}/activity`:null),summary=useResource('/telecaller/summary');
 const save=async()=>{try{await shared.write('post',`/telecaller/customers/${person.id}/action`,form);await r.load();await activity.load();setError('');}catch(e){setError(errMsg(e));}};
 return <><PageTitle>Lead CRM</PageTitle><State resource={r} id="leads"/><Notice id="leads-error">{error}</Notice><div className="filters"><Field name="lead-search" value={f.search} onChange={v=>setF({...f,search:v,page:1})}/><Field name="lead-status" options={[{value:'',label:'All leads'},'new','contacted','interested','not_interested','follow_up_required','converted']} value={f.lead_status} onChange={v=>setF({...f,lead_status:v,page:1})}/></div>
 <State resource={summary} id="lead-summary"/>{summary.data&&<div className="metrics-strip"><div>Assigned customer cohort<strong data-testid="lead-cohort-total">{summary.data.total_customers}</strong></div><div>Follow-ups due · canonical UTC day<strong data-testid="lead-followups-due">{summary.data.follow_ups_due}</strong></div><div>Actions today · canonical UTC day<strong data-testid="lead-actions-today">{summary.data.actions_today}</strong></div>{Object.entries(summary.data.by_status||{}).map(([k,v])=><div key={k}>{k.replace(/_/g,' ')}<strong data-testid={`lead-summary-${k}`}>{v}</strong></div>)}</div>}
 <Table id="leads" rows={r.data?.customers||[]} columns={[{key:'name',title:'Customer'},{key:'shop_name',title:'Shop'},{key:'phone',title:'Phone'},{key:'lead_status',title:'Lead status'},{key:'open',title:'Activity',render:u=><Button variant="outline" data-testid={`lead-open-${u.id}`} onClick={()=>setPerson(u)}>Open lead</Button>}]}/><Pager {...r.data} id="leads" page={f.page} onPage={page=>setF({...f,page})}/>
 {person&&<section className="app-dialog"><h2>{person.name}</h2><div className="fields-grid"><Field name="lead-action" options={['note','call','whatsapp','status_change','follow_up']} value={form.action} onChange={v=>setForm({...form,action:v})}/><Field name="lead-new-status" options={[{value:'',label:'Unchanged'},'new','contacted','interested','not_interested','follow_up_required','converted']} value={form.new_status} onChange={v=>setForm({...form,new_status:v})}/><Field name="lead-notes" value={form.notes} onChange={v=>setForm({...form,notes:v})}/><Field name="lead-follow-up" title="Follow-up · ISO timestamp with timezone" value={form.follow_up_at} onChange={v=>setForm({...form,follow_up_at:v})}/></div><Button data-testid="lead-save" onClick={save}>Record activity</Button><Button variant="ghost" data-testid="lead-close" onClick={()=>setPerson(null)}>Close</Button><State resource={activity} id="lead-activity"/><p className="text-xs mt-4" data-testid="lead-history-limit">Up to 100 recent activity entries.</p><Table id="lead-activity" rows={activity.data?.activities||[]} columns={[{key:'action',title:'Action'},{key:'notes',title:'Note'},{key:'created_at',title:'Time',render:e=>ist(e.created_at)}]}/></section>}</>;
}