import React,{useRef,useState} from 'react';
import {useVirtualizer} from '@tanstack/react-virtual';
import {Link} from 'react-router-dom';
import {PageTitle,State,useResource,Field,Pager,Notice,changed} from '@/components/admin/SharedUI';
import {ProductFields,NEW_PRODUCT} from '@/components/admin/ProductFields';
import {PrivateImage} from '@/components/admin/PrivateImage';
import {shared,api,errMsg} from '@/lib/api';
import {Button} from '@/components/ui/button';
export default function Products(){
 const [f,setF]=useState({page:1,limit:40,mode:'catalog',include_hidden:true,metal_type:'silver'}),r=useResource('/products',f),categories=useResource('/categories');
 const [editor,setEditor]=useState(null),[original,setOriginal]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const scroller=useRef(null);const items=r.data?.products||[];
 const virtual=useVirtualizer({count:items.length,getScrollElement:()=>scroller.current,estimateSize:()=>150,overscan:3});
 const set=(k,v)=>{setF({...f,[k]:v,page:1});scroller.current?.scrollTo(0,0);};
 const edit=async p=>{try{const full=await shared.get(`/products/${p.id}`);setOriginal(full);setEditor(Object.fromEntries(Object.keys({...NEW_PRODUCT,...full}).filter(k=>['product_code','title','metal_type','category','description','subcategory','approx_weight','purity','selling_touch','selling_label','stock_status','tags','video_url','visibility','is_new_arrival','is_trending','is_pinned','images','base_metal','stone_weight_ct'].includes(k)).map(k=>[k,full[k]])));}catch(e){setError(errMsg(e));}};
 const save=async()=>{setBusy(true);setError('');try{await shared.write(original.id?'put':'post',original.id?`/products/${original.id}`:'/products',original.id?{...changed(original,editor),version:original.version}:editor);setEditor(null);await r.load();}catch(e){setError(errMsg(e));if(e.response?.status===409){setEditor(null);await r.load();}}finally{setBusy(false);}};
 const photo=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8*1024*1024){setError('Maximum image size is 8 MiB.');return;}setBusy(true);try{const data=new FormData();data.append('file',file);const r=await api.post('/bff/products/upload-image',data);setEditor(s=>({...s,images:[...(s.images||[]),r.data.url]}));}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
 return <><PageTitle actions={<><Button onClick={()=>{setOriginal({});setEditor({...NEW_PRODUCT,images:[]});}} data-testid="product-add">Add product</Button><Button asChild variant="outline"><Link to="/admin/pdf-import" data-testid="products-import">PDF import</Link></Button></>}>Collections</PageTitle><State resource={r} id="products"/><Notice id="products-error">{error}</Notice>
 <div className="filters"><Field name="products-metal" title="Metal" options={['silver','gold','diamond',{value:'',label:'All metals'}]} value={f.metal_type} onChange={v=>set('metal_type',v)}/><Field name="products-category" options={[{value:'',label:'All categories'},...(categories.data?.categories||[])]} value={f.category} onChange={v=>set('category',v)}/><Field name="products-search" title="Indexed word search" value={f.search} onChange={v=>set('search',v)}/><Field name="products-code" title="Exact product_code · case sensitive" value={f.product_code} onChange={v=>set('product_code',v)}/></div>
 <div ref={scroller} style={{height:520,overflow:'auto',position:'relative',background:'white'}} data-testid="product-virtual-list"><div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(row=>{const p=items[row.index];return <article key={p.id} className="product-row" style={{height:150,transform:`translateY(${row.start}px)`}} data-testid={`product-${p.id}`}><PrivateImage id={`product-thumb-${p.id}`} src={p.thumbnail_path||p.storage_path||p.images?.[0]} alt={p.title}/><div className="min-w-0"><h2 className="break-words">{p.title}</h2><p className="text-xs break-words">{p.product_code||'Legacy · no SKU'} · {p.metal_type} · {p.category}</p><p className="text-xs" data-testid={`product-visibility-${p.id}`}>{p.visibility==='hidden'?'Hidden draft':'Published'} · {p.approx_weight}</p></div><Button variant="outline" onClick={()=>edit(p)} data-testid={`product-edit-${p.id}`}>Edit & photos</Button></article>;})}</div>{!items.length&&!r.busy&&<p data-testid="products-empty" className="p-8">No matching products.</p>}</div>
 <Pager {...r.data} id="products" page={f.page} onPage={page=>{setF({...f,page});scroller.current?.scrollTo(0,0);}}/>
 {editor&&<section className="app-dialog" data-testid="product-editor"><h2>{original.id?'Edit product':'New hidden product'}</h2><ProductFields value={editor} onChange={setEditor}/>{original.storage_path&&<div className="max-w-xs"><p>Original scan · preserved</p><PrivateImage id="original-scan" src={original.original_source_storage_path||original.storage_path}/></div>}
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 my-4">{(editor.images||[]).map((src,i)=><div key={src+i}><PrivateImage id={`gallery-photo-${i}`} src={src}/><Button variant="ghost" data-testid={`gallery-remove-${i}`} onClick={()=>setEditor({...editor,images:editor.images.filter((_,n)=>n!==i)})}>Remove additional photo</Button></div>)}</div>
 <label className="field mb-4">Add photograph · JPG/PNG/WEBP/GIF, 8 MiB<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={photo} disabled={busy||(editor.images||[]).length>=20} data-testid="product-photo-upload"/></label>
 <Button disabled={busy} onClick={save} data-testid="product-save">Save changes</Button><Button variant="ghost" data-testid="product-cancel" onClick={()=>setEditor(null)}>Cancel</Button></section>}</>;
}