import React,{useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {useAdmin} from '@/components/admin/AdminLayout';
import {PageTitle,State,useResource,Field,Pager,Table,ist,duration,label,todayIST} from '@/components/admin/SharedUI';
import {QueryMetrics} from '@/components/admin/QueryMetrics';
import {QueryDetail} from '@/components/admin/QueryDetail';
import {Button} from '@/components/ui/button';
export default function Queries(){
  const {me}=useAdmin(),[url]=useSearchParams(),[f,setF]=useState({page:1,limit:20,status:'open',view:'all',sort:'oldest',search:url.get('search')||''}),[id,setId]=useState(null),[range,setRange]=useState({start:todayIST(),end:todayIST()});
  const r=useResource('/requests',Object.fromEntries(Object.entries(f).filter(([,v])=>v!=='')),true),catalog=useResource('/requests/catalog'),staff=useResource('/requests/staff-options'),active=useResource(me.role==='admin'?'/integrations/staff':null,{role:'telecaller',status:'active'});
  const set=(k,v)=>setF(s=>({...s,[k]:v,page:1}));const people=staff.data?.users||[],opts=[{value:'',label:'All'},...people.map(u=>({value:u.id,label:u.name}))];
  const drill=(person,start,end)=>{setF({page:1,limit:20,status:'all',sort:'oldest',search:f.search,request_type:f.request_type||'',period_resolver:person,period_start:start,period_end:end});window.scrollTo({top:0,behavior:'smooth'});};
  return <><PageTitle>Customer enquiries</PageTitle><State resource={r} id="queries"/>
    <div className="flex flex-wrap gap-2 mt-4">{['all','mine','unassigned'].map(v=><Button key={v} variant={f.view===v?'default':'outline'} onClick={()=>set('view',v)} data-testid={`query-view-${v}`}>{label(v)}</Button>)}</div>
    <div className="filters"><Field name="query-search" title="Name, phone, shop, place" value={f.search} onChange={v=>set('search',v)}/><Field name="query-type" options={[{value:'',label:'All types'},...(catalog.data?.types||[])]} value={f.request_type} onChange={v=>set('request_type',v)}/><Field name="query-status" options={['all','open',...(catalog.data?.statuses||[])]} value={f.status} onChange={v=>set('status',v)}/><Field name="query-sort" title="Waiting order" options={['oldest','newest','longest_wait']} value={f.sort} onChange={v=>set('sort',v)}/>
    {['assignee','resolver'].map(k=><Field key={k} name={`query-${k}`} options={opts} value={f[k]} onChange={v=>set(k,v)}/>)}
    {['created_from','created_to','resolved_from','resolved_to'].map(k=><Field key={k} name={`query-${k}`} title={`${label(k)} · IST`} type="date" value={f[k]} onChange={v=>set(k,v)}/>)}
    {['min_age_minutes','max_age_minutes'].map(k=><Field key={k} name={`query-${k}`} title={label(k)} type="number" min="0" value={f[k]} onChange={v=>set(k,v)}/>)}</div>
    {f.period_resolver&&<div data-testid="query-period-drilldown" className="notice">Resolution events: {people.find(u=>u.id===f.period_resolver)?.name||f.period_resolver} · {f.period_start} to {f.period_end}<Button variant="link" data-testid="query-clear-drilldown" onClick={()=>setF({page:1,limit:20,status:'open',view:'all',sort:'oldest'})}>Clear</Button></div>}
    <div className="flex flex-wrap gap-2">{(catalog.data?.types||[]).map(t=><Button key={t} variant="outline" data-testid={`query-count-${t}`} onClick={()=>{set('request_type',t);set('status','open');}}>{label(t)} · {r.data?.open_counts_by_type?.[t]??0}</Button>)}</div>
    <Table id="queries" rows={r.data?.requests||[]} columns={[{key:'customer_name',title:'Customer',render:q=><Button variant="link" data-testid={`query-open-${q.id}`} onClick={()=>setId(q.id)}>{q.customer_name||q.user_name||'Unknown'}<br/>{q.customer_phone||q.user_phone}</Button>},{key:'customer_shop_name',title:'Shop / Place',render:q=>`${q.customer_shop_name||q.shop_name||'—'} / ${q.customer_location||q.user_city||'—'}`},{key:'request_type',title:'Type',render:q=>label(q.request_type)},{key:'status',title:'Status',render:q=>label(q.status)},{key:'created_at',title:'Created · IST',render:q=>ist(q.created_at)},{key:'pending_seconds',title:'Current wait',render:q=>duration(q.pending_seconds)},{key:'assignee_id',title:'Assignee',render:q=>q.assignee_name||people.find(p=>p.id===q.assignee_id)?.name||'Unassigned'},{key:'resolver_id',title:'Resolver',render:q=>q.resolver_name||people.find(p=>p.id===q.resolver_id)?.name||'—'}]}/><Pager id="queries" {...r.data} page={f.page} onPage={page=>setF({...f,page})}/>
    {id&&<QueryDetail key={id} id={id} me={me} catalog={catalog.data} options={[...people.filter(u=>!(active.data?.users||[]).some(a=>a.id===u.id)),...(active.data?.users||[])]} onClose={()=>setId(null)} onChanged={r.load}/>}
    {me.role!=='billing_executive'&&<QueryMetrics range={range} setRange={setRange} search={f.search||''} requestType={f.request_type||''} onDrill={drill}/>}
  </>;
}