import React,{useEffect,useState} from 'react';
import {PageTitle,State,useResource,Field,Table,Notice,Check,changed,ist} from '@/components/admin/SharedUI';
import {Button} from '@/components/ui/button';
import {shared,errMsg} from '@/lib/api';
import {RateHistory} from '@/components/admin/RateHistory';
// MCX is displayed and edited in market units (silver INR/kg, gold INR/10g) through `{metal}_mcx_display_rate`; the app
// converts to its canonical INR/g basis. The INR/g `{metal}_mcx_rate` is never sent from this page.
const numbers=['physical_rate','mcx_display_rate','dollar_rate','physical_premium'];
const EDITABLE=/^(silver|gold)_(physical_rate|mcx_display_rate|dollar_rate|physical_premium|purity|physical_mode|physical_base|movement)$/;
const unit=(data,m,k)=>k==='dollar_rate'?'USD/troy_oz':k==='mcx_display_rate'?(data[`${m}_mcx_display_unit`]||(m==='silver'?'INR/kg':'INR/10g')):'INR/g';
export default function Rates(){
  const r=useResource('/rates/latest'),slabs=useResource('/rate-list'),audit=useResource('/rates/audit',{page:1,limit:30});
  const [form,setForm]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[slab,setSlab]=useState(null),[original,setOriginal]=useState({}),[confirmUnits,setConfirmUnits]=useState(false);
  useEffect(()=>{if(r.data)setForm(Object.fromEntries(Object.entries(r.data).filter(([k])=>EDITABLE.test(k))));},[r.data]);
  const save=async()=>{setBusy(true);setError('');try{const body={...changed(r.data,form),version:r.data.version};for(const m of ['silver','gold']){delete body[`${m}_mcx_rate`];delete body[`${m}_mcx_display_unit`];}if(confirmUnits)body.mcx_basis_confirmed=true;await shared.write('post','/rates',body);setConfirmUnits(false);await r.load();await audit.load();}catch(e){setError(errMsg(e));if(e.response?.status===409)await r.load();}finally{setBusy(false);}};
  const saveSlab=async()=>{setBusy(true);try{const data=original.id?{...changed(original,slab),version:original.version}:slab;delete data.id;await shared.write(original.id?'put':'post',original.id?`/rate-list/${original.id}`:'/rate-list',data);setSlab(null);await slabs.load();}catch(e){setError(errMsg(e));if(e.response?.status===409){setSlab(null);await slabs.load();}}finally{setBusy(false);}};
  const remove=async s=>{if(!window.confirm(`Soft-delete ${s.item_name}?`))return;try{await shared.write('delete',`/rate-list/${s.id}`,null,{version:s.version});await slabs.load();}catch(e){setError(errMsg(e));await slabs.load();}};
  const mcxTouched=['silver','gold'].some(m=>changed(r.data||{},form)[`${m}_mcx_display_rate`]!==undefined);
  return <><PageTitle>Rates & Slabs</PageTitle><State resource={r} id="rates"/><Notice id="rates-error">{error}</Notice>
    {r.data&&<><p className="text-xs mt-4" data-testid="rates-version">Version {r.data.version} · Effective {ist(r.data.effective_at||r.data.updated_at)}</p>
    <p className="text-xs text-slate-500" data-testid="rates-units">Units: physical prices and premium in INR/g · MCX silver in {r.data.silver_mcx_display_unit||'INR/kg'} and MCX gold in {r.data.gold_mcx_display_unit||'INR/10g'} (the app stores INR/g and converts) · USD reference per troy ounce.</p>
    {r.data.mcx_units_verified===false&&<div className="notice mt-3" data-testid="rates-mcx-unverified">The stored MCX values were entered before unit-aware editing, so their unit basis is unconfirmed. The numbers shown are the stored INR/g values converted to {r.data.silver_mcx_display_unit||'INR/kg'} / {r.data.gold_mcx_display_unit||'INR/10g'}; nothing was reinterpreted. Check them against the market quote and save the MCX rate in the stated unit (or tick the confirmation below) to confirm the basis.
      <div className="mt-2"><Check id="rates-confirm-units" value={confirmUnits} onChange={setConfirmUnits}>I have checked the MCX values shown and confirm they are correct in these units</Check></div></div>}
    {['silver','gold'].map(m=><section key={m} className="detail-section"><h2 className="capitalize">{m}</h2><div className="fields-grid">{numbers.map(k=><Field key={k} name={`${m}-${k}`} title={`${k==='mcx_display_rate'?'MCX rate':k.replace(/_/g,' ')} · ${unit(r.data,m,k)}`} type="number" min="0" step="any" value={form[`${m}_${k}`]} onChange={v=>setForm({...form,[`${m}_${k}`]:v===''?'':Number(v)})}/>)}<Field name={`${m}-purity`} title="Purity" value={form[`${m}_purity`]} onChange={v=>setForm({...form,[`${m}_purity`]:v})}/><Field name={`${m}-mode`} title="Physical mode" options={[{value:'',label:'Unchanged'},'manual','calculated']} value={form[`${m}_physical_mode`]} onChange={v=>setForm({...form,[`${m}_physical_mode`]:v,...(v==='calculated'?{[`${m}_physical_base`]:'mcx'}:{})})}/><Field name={`${m}-movement`} title="Movement" options={[{value:'',label:'Unchanged'},'up','down','stable']} value={form[`${m}_movement`]} onChange={v=>setForm({...form,[`${m}_movement`]:v})}/></div>
      <p className="text-xs text-slate-500" data-testid={`${m}-mcx-canonical`}>Stored MCX basis: {r.data[`${m}_mcx_rate`]} INR/g{mcxTouched?' · will be recomputed by the app from the value you enter':''}</p></section>)}<Button disabled={busy} onClick={save} data-testid="rates-save">Save changed rates</Button></>}
    <section className="detail-section"><h2>Rate list · labour in original units</h2><State resource={slabs} id="slabs"/><Button className="mt-3" onClick={()=>{setOriginal({});setSlab({item_name:'',metal_type:'silver',labour:{currency:'INR',amount:'',basis:'kg'}});}} data-testid="slab-add">Add slab</Button><Table id="slabs" rows={slabs.data?.slabs||[]} columns={[{key:'item_name',title:'Item'},{key:'metal_type',title:'Metal'},{key:'purity',title:'Purity'},{key:'labour_display',title:'Labour',render:s=><>{s.labour_display||s.labour_kg||'—'}{s.unit_review_required&&<strong data-testid={`slab-unit-review-${s.id}`}> · Unit review required</strong>}</>},{key:'actions',title:'Actions',render:s=><><Button variant="outline" data-testid={`slab-edit-${s.id}`} onClick={()=>{setOriginal(s);setSlab(Object.fromEntries(['item_name','metal_type','category','subcategory','purity','wastage','order','labour'].filter(k=>s[k]!=null).map(k=>[k,s[k]])));}}>Edit</Button><Button variant="ghost" data-testid={`slab-delete-${s.id}`} onClick={()=>remove(s)}>Delete</Button></>}]}/></section>
    {slab&&<section className="app-dialog" data-testid="slab-editor"><h2>Slab details</h2><div className="fields-grid">{['item_name','category','subcategory','purity','wastage'].map(k=><Field key={k} name={`slab-${k}`} value={slab[k]} onChange={v=>setSlab({...slab,[k]:v})}/>)}<Field name="slab-metal" options={['silver','gold','diamond']} value={slab.metal_type} onChange={v=>setSlab({...slab,metal_type:v})}/><Field name="slab-order" type="number" value={slab.order} onChange={v=>setSlab({...slab,order:Number(v)})}/><Field name="slab-labour-amount" title="Labour amount · INR" value={slab.labour?.amount} onChange={v=>setSlab({...slab,labour:{currency:'INR',basis:slab.labour?.basis||'kg',amount:v}})}/><Field name="slab-labour-basis" options={['kg','10g','piece']} value={slab.labour?.basis||'kg'} onChange={v=>setSlab({...slab,labour:{currency:'INR',amount:slab.labour?.amount||'',basis:v}})}/></div><Button disabled={busy} onClick={saveSlab} data-testid="slab-save">Save slab</Button><Button variant="ghost" onClick={()=>setSlab(null)} data-testid="slab-cancel">Cancel</Button></section>}
    <section className="detail-section"><h2>Recent rate audit · up to 30 events</h2><State resource={audit} id="rate-audit"/><Table id="rate-audit" rows={audit.data?.events||[]} columns={[{key:'actor_id',title:'Actor'},{key:'actor_role',title:'Role'},{key:'at',title:'Time',render:e=>ist(e.at)},{key:'changes',title:'Changed fields',render:e=>Object.entries(e.changes||{}).map(([k,v])=>`${k}: ${v}${/_mcx_rate$/.test(k)?' INR/g':''}`).join(' · ')}]}/></section>
    <RateHistory/>
  </>;
}
