import React,{useState} from 'react';
import {useAdmin} from '@/components/admin/AdminLayout';
import {PageTitle,State,useResource,Field,Table,Notice,ist} from '@/components/admin/SharedUI';
import {shared,errMsg} from '@/lib/api';
import {Button} from '@/components/ui/button';
export default function Rewards(){const {me}=useAdmin(),[id,setId]=useState(''),[selected,setSelected]=useState(''),[form,setForm]=useState({points:1,reason:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const history=useResource(selected?`/rewards/customer/${selected}`:null),config=useResource(me.role==='admin'?'/rewards/config':null),[edit,setEdit]=useState(null);
 const transact=async kind=>{if(!window.confirm(`Confirm ${kind} of ${form.points} points for ${history.data?.customer?.name}?`))return;setBusy(true);try{await shared.write('post',`/rewards/${kind}`,{user_id:selected,...form});await history.load();setError('');}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
 const saveConfig=async()=>{setBusy(true);try{await shared.write('post','/rewards/config',edit);setEdit(null);await config.load();}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
 return <><PageTitle>Rewards & Billing</PageTitle><Notice id="reward-error">{error}</Notice>
 <CustomerSearch onPick={c=>{setId(c.id);setSelected(c.id);}}/>
 <div className="filters"><Field name="reward-customer-id" title="Canonical customer ID" value={id} onChange={setId}/></div><Button data-testid="reward-load-customer" disabled={!id} onClick={()=>setSelected(id)}>Load customer balance</Button><State resource={history} id="reward-history"/>
 {history.data&&<><div className="metrics-strip"><div>{history.data.customer.name}<strong data-testid="reward-balance">{history.data.customer.reward_points} points</strong></div></div><div className="filters"><Field name="reward-points" type="number" min="1" value={form.points} onChange={v=>setForm({...form,points:Number(v)})}/><Field name="reward-reason" value={form.reason} onChange={v=>setForm({...form,reason:v})}/></div><div className="flex gap-2"><Button data-testid="reward-credit" disabled={busy||form.points<=0} onClick={()=>transact('credit')}>Credit points</Button><Button variant="outline" data-testid="reward-deduct" disabled={busy||form.points<=0} onClick={()=>transact('deduct')}>Deduct points</Button></div><p className="text-xs mt-4" data-testid="reward-history-scope">Up to 100 recent transactions; returned earned/deducted summaries cover that recent history, not lifetime.</p><Table id="reward-transactions" rows={history.data.transactions||[]} columns={[{key:'type',title:'Type'},{key:'points',title:'Points'},{key:'reason',title:'Reason'},{key:'created_at',title:'Time',render:e=>ist(e.created_at)}]}/></>}
 {me.role==='admin'&&<section className="detail-section"><h2>Reward settings</h2><State resource={config} id="reward-config"/>{config.data&&!edit&&<Button className="mt-4" data-testid="reward-edit-config" onClick={()=>setEdit(config.data)}>Edit configuration</Button>}{edit&&<><div className="fields-grid">{['points_per_1000','welcome_bonus','first_purchase_bonus','first_video_bonus'].map(k=><Field key={k} name={`reward-${k}`} type="number" min="0" value={edit[k]} onChange={v=>setEdit({...edit,[k]:Number(v)})}/>)}<Field name="reward-eligible-types" value={(edit.eligible_types||[]).join(',')} onChange={v=>setEdit({...edit,eligible_types:v.split(',').map(s=>s.trim())})}/></div><Button data-testid="reward-save-config" disabled={busy} onClick={saveConfig}>Save configuration</Button></>}</section>}</>;
}

export function CustomerSearch({onPick}){
  const [q,setQ]=useState('');const term=q.trim();const r=useResource(term.length>=2?'/customers/search':null,{q:term});
  const minimum=r.data?.minimum_length??2,limit=r.data?.limit??20,rows=r.data?.customers||[];
  return <div className="detail-section"><h2>Find customer</h2><div className="filters"><Field name="reward-customer-search" title="Name, phone, customer code, shop or place" value={q} onChange={setQ}/></div>
    <p className="text-xs text-slate-500" data-testid="reward-search-scope">{term.length<minimum?`Type at least ${minimum} characters.`:`Showing up to ${limit} canonical matches for “${r.data?.query??term}”.`}</p>
    {term.length>=2&&<State resource={r} id="reward-search"/>}
    {term.length>=2&&<Table id="reward-search" rows={rows} columns={[{key:'name',title:'Customer',render:c=><Button variant="link" data-testid={`reward-search-pick-${c.id}`} onClick={()=>onPick(c)}>{c.name||'Unnamed'}</Button>},{key:'phone',title:'Phone'},{key:'customer_code',title:'Code',render:c=>c.customer_code||c.code||'—'},{key:'shop_name',title:'Shop'},{key:'location',title:'Place',render:c=>c.location||c.city||'—'}]}/>}
  </div>;
}