import React,{useEffect,useState} from 'react';
import {api,errMsg} from '@/lib/api';
import {PageTitle,Notice,Table,useResource,State} from '@/components/admin/SharedUI';
import {Button} from '@/components/ui/button';
export default function Settings(){const [health,setHealth]=useState(null),[result,setResult]=useState(null),[error,setError]=useState('');const deletions=useResource('/admin/deletion-requests'),reports=useResource('/admin/ai/reports');
 useEffect(()=>{api.get('/health').then(r=>setHealth(r.data)).catch(e=>setError(errMsg(e)));},[]);
 const reconcile=async()=>{try{setResult((await api.post('/admin/deletions/reconcile')).data);}catch(e){setError(errMsg(e));}};
 return <><PageTitle>Settings & Privacy</PageTitle><Notice>{error}</Notice><p className="text-sm" data-testid="website-build">Website build: {health?.build} · commit {health?.commit}</p><p className="text-xs break-all" data-testid="contract-commit">App contract: {health?.app_contract_commit}</p>
 <Table id="config-presence" rows={Object.entries(health?.configuration||{}).map(([name,present])=>({id:name,name,present:present?'Present':'Not configured'}))} columns={[{key:'name',title:'Website setting'},{key:'present',title:'Presence only'}]}/><Notice id="configuration-boundary">Settings are private operator-managed. Presence does not prove matching two-sided keys, data isolation or real SMS delivery. No canonical service key is editable in this browser.</Notice>
 <section className="detail-section"><h2>Deletion cleanup acknowledgements</h2><Button className="my-4" data-testid="deletion-reconcile" onClick={reconcile}>Process canonical deletion events</Button>{result&&<p data-testid="deletion-reconcile-result">Acknowledged: {result.acknowledged}. Blocked private linkage review: {result.blocked_private_linkage_review}. External erasure is not complete.</p>}<State resource={deletions} id="deletion-requests"/><Table id="deletion-requests" rows={deletions.data?.requests||[]} columns={[{key:'reference',title:'Reference'},{key:'status',title:'Status'}]}/></section>
 <section className="detail-section"><h2>Assistant moderation reports</h2><State resource={reports} id="moderation"/><Table id="moderation" rows={reports.data?.reports||[]} columns={[{key:'reason',title:'Reason'},{key:'status',title:'Status'},{key:'created_at',title:'Created'}]}/></section></>;
}