import React,{useEffect,useState} from 'react';
import {api,errMsg} from '@/lib/api';
import {PageTitle,Notice,Table,useResource,State} from '@/components/admin/SharedUI';
import {Button} from '@/components/ui/button';
export default function Settings(){const [health,setHealth]=useState(null),[result,setResult]=useState(null),[error,setError]=useState('');const deletions=useResource('/admin/deletion-requests'),reports=useResource('/admin/ai/reports');
 useEffect(()=>{api.get('/health').then(r=>setHealth(r.data)).catch(e=>setError(errMsg(e)));},[]);
 const reconcile=async()=>{try{setResult((await api.post('/admin/deletions/reconcile')).data);}catch(e){setError(errMsg(e));}};
 return <><PageTitle>Settings & Privacy</PageTitle><Notice>{error}</Notice><p className="text-sm" data-testid="website-build">Website build: {health?.build} · commit {health?.commit}</p><p className="text-xs break-all" data-testid="contract-commit">App contract: {health?.app_contract_commit}</p>
 <section className="detail-section" data-testid="canonical-connection"><h2>Canonical app connection</h2>
  <p className="text-sm" data-testid="upstream-build">App build: {health?.upstream?.reachable?`${health.upstream.build} · commit ${health.upstream.commit}`:'not reachable'}</p>
  <Table id="upstream-capabilities" rows={Object.entries(health?.upstream?.capabilities||{}).map(([name,on])=>({id:name,name,state:on?'Advertised':'Absent'}))} columns={[{key:'name',title:'App capability'},{key:'state',title:'State'}]}/>
  <Table id="flow-readiness" rows={Object.entries(health?.flows||{}).map(([name,f])=>({id:name,name,ready:f.ready?'Ready':'Unavailable',verified:f.credential_verified===true?'Verified':f.credential_verified===false?'Rejected':'Not checked',issues:(f.issues||[]).join(', ')||'—'}))} columns={[{key:'name',title:'Website flow'},{key:'ready',title:'State'},{key:'verified',title:'Key matching'},{key:'issues',title:'Issue names'}]}/>
  <p className="text-sm" data-testid="owner-admin-state">Default administrator bootstrap (app-side): {health?.upstream?.owner_admin?.reported?`${health.upstream.owner_admin.state||'not applied'}${health.upstream.owner_admin.phone_suffix?` · phone ending ${health.upstream.owner_admin.phone_suffix}`:''}${health.upstream.owner_admin.issues?.length?` · ${health.upstream.owner_admin.issues.join(', ')}`:''}`:'not reported by this app build'}</p>
  <Notice id="owner-admin-boundary">The default administrator is applied by the canonical app at its start. This website only reads the role from canonical /auth/me after the staff OTP exchange; it never promotes or stores a local admin.</Notice></section>
 <Table id="config-presence" rows={Object.entries(health?.configuration||{}).map(([name,present])=>({id:name,name,present:present?'Present':'Not configured'}))} columns={[{key:'name',title:'Website setting'},{key:'present',title:'Presence only'}]}/><Notice id="configuration-boundary">Settings are private operator-managed. Presence does not prove matching two-sided keys, data isolation or real SMS delivery. No canonical service key is editable in this browser.</Notice>
 <section className="detail-section"><h2>Deletion cleanup acknowledgements</h2><Button className="my-4" data-testid="deletion-reconcile" onClick={reconcile}>Process canonical deletion events</Button>{result&&<p data-testid="deletion-reconcile-result">Acknowledged: {result.acknowledged}. Blocked private linkage review: {result.blocked_private_linkage_review}. External erasure is not complete.</p>}<State resource={deletions} id="deletion-requests"/><Table id="deletion-requests" rows={deletions.data?.requests||[]} columns={[{key:'reference',title:'Reference'},{key:'status',title:'Status'}]}/></section>
 <section className="detail-section"><h2>Assistant moderation reports</h2><State resource={reports} id="moderation"/><Table id="moderation" rows={reports.data?.reports||[]} columns={[{key:'reason',title:'Reason'},{key:'status',title:'Status'},{key:'created_at',title:'Created'}]}/></section></>;
}