import React,{useState} from 'react';
import {PageTitle,State,useResource,Field,Table,Notice,changed} from '@/components/admin/SharedUI';
import {shared,errMsg} from '@/lib/api';
import {Button} from '@/components/ui/button';
const empty={name:'',phone:'',role:'telecaller',code:'',status:'active'};
export default function Staff(){
  const r=useResource('/integrations/staff'),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[conversion,setConversion]=useState(null);
  const save=async()=>{setBusy(true);setError('');try{await shared.write(selected?'patch':'post',selected?`/integrations/staff/${selected.id}`:'/integrations/staff',selected?changed(selected,form):form);setForm(null);await r.load();}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
  const disable=async u=>{if(!window.confirm(`Disable ${u.name}? Canonical history will be preserved.`))return;try{await shared.write('delete',`/integrations/staff/${u.id}`);await r.load();}catch(e){setError(errMsg(e));}};
  const convert=async()=>{setBusy(true);try{await shared.write('post',`/integrations/staff/${conversion.id}/convert`,{role:conversion.role,reason:conversion.reason,confirm_user_id:conversion.confirm});setConversion(null);await r.load();}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
  return <><PageTitle actions={<><Button data-testid="staff-add" onClick={()=>{setSelected(null);setForm({...empty});}}>Add staff</Button><Button variant="outline" data-testid="staff-convert-open" onClick={()=>setConversion({id:'',role:'telecaller',reason:'',confirm:''})}>Convert existing customer</Button></>}>Staff directory</PageTitle><State resource={r} id="staff"/><Notice id="staff-error">{error}</Notice>
    <Table id="staff" rows={r.data?.users||[]} columns={[{key:'name',title:'Name'},{key:'phone',title:'Phone'},{key:'role',title:'Role'},{key:'status',title:'Account'},{key:'actions',title:'Actions',render:u=><div className="flex gap-2"><Button variant="outline" data-testid={`staff-edit-${u.id}`} onClick={()=>{setSelected(u);setForm(Object.fromEntries(Object.keys(empty).map(k=>[k,u[k]||''])));}}>Edit</Button><Button variant="outline" data-testid={`staff-disable-${u.id}`} onClick={()=>disable(u)}>Disable</Button></div>}]}/>
    {form&&<section className="app-dialog" data-testid="staff-editor"><h2>{selected?'Edit staff':'Create staff identity'}</h2><div className="fields-grid">{['name','phone','code'].map(k=><Field key={k} name={`staff-${k}`} disabled={!!selected&&k==='phone'} value={form[k]} onChange={v=>setForm({...form,[k]:v})}/>)}<Field name="staff-role" options={['admin','telecaller','billing_executive']} value={form.role} onChange={v=>setForm({...form,role:v})}/><Field name="staff-status" options={['active','inactive']} value={form.status} onChange={v=>setForm({...form,status:v})}/></div><Button disabled={busy} onClick={save} data-testid="staff-save">Save</Button><Button variant="ghost" data-testid="staff-cancel" onClick={()=>setForm(null)}>Cancel</Button></section>}
    {conversion&&<section className="app-dialog" data-testid="staff-conversion"><h2>Explicit customer conversion</h2><p>Preserves the existing canonical identity. Confirm the exact ID and reason.</p><div className="fields-grid">{['id','reason','confirm'].map(k=><Field key={k} name={`conversion-${k}`} title={k==='confirm'?'Retype canonical ID':k} value={conversion[k]} onChange={v=>setConversion({...conversion,[k]:v})}/>)}<Field name="conversion-role" options={['admin','telecaller','billing_executive']} value={conversion.role} onChange={v=>setConversion({...conversion,role:v})}/></div><Button disabled={busy||!conversion.id||conversion.id!==conversion.confirm||conversion.reason.length<10} onClick={convert} data-testid="conversion-submit">Confirm conversion</Button><Button variant="ghost" onClick={()=>setConversion(null)} data-testid="conversion-cancel">Cancel</Button></section>}
  </>;
}